import 'package:dalili/core/localization/generated/l10n.dart';

class AppLocalizations {
  AppLocalizations._();

  static String get appName => S.current.appName;
  static String get searchHint => S.current.searchHint;
  static String get welcomeTitle => S.current.welcomeTitle;
  static String get welcomeSubtitle => S.current.welcomeSubtitle;
  static String get departments => S.current.departments;
  static String get viewAll => S.current.viewAll;
  static String get suggestedBooks => S.current.suggestedBooks;
  static String get scanBook => S.current.scanBook;
  static String get indoorNav => S.current.indoorNav;
  static String get searchBooks => S.current.searchBooks;
  static String get relatedArticles => S.current.relatedArticles;
  static String get bookNotFound => S.current.bookNotFound;
  static String get noArticles => S.current.noArticles;
  static String get noFavorites => S.current.noFavorites;
  static String get noResults => S.current.noResults;
  static String get loading => S.current.loading;
  static String get error => S.current.error;
  static String get retry => S.current.retry;
  static String get favorites => S.current.favorites;
  static String get settings => S.current.settings;
  static String get home => S.current.home;
  static String get navigation => S.current.navigation;
  static String get language => S.current.language;
  static String get theme => S.current.theme;
  static String get lightTheme => S.current.lightTheme;
  static String get darkTheme => S.current.darkTheme;
  static String get arabic => S.current.arabic;
  static String get english => S.current.english;
  static String get selectLanguage => S.current.selectLanguage;
  static String get continueBtn => S.current.continueBtn;
  static String get skip => S.current.skip;
  static String get onboardScanTitle => S.current.onboardScanTitle;
  static String get onboardScanDesc => S.current.onboardScanDesc;
  static String get onboardNavTitle => S.current.onboardNavTitle;
  static String get onboardNavDesc => S.current.onboardNavDesc;
  static String get getStarted => S.current.getStarted;
  static String get publisher => S.current.publisher;
  static String get year => S.current.year;
  static String get edition => S.current.edition;
  static String get bookLanguage => S.current.bookLanguage;
  static String get classification => S.current.classification;
  static String get scanInstruction => S.current.scanInstruction;
  static String get bookRecognized => S.current.bookRecognized;
  static String get pointCameraAtBook => S.current.pointCameraAtBook;
  static String get scanHintBottom => S.current.scanHintBottom;
  static String get author => S.current.author;
  static String get department => S.current.department;
  static String get shelf => S.current.shelf;
  static String get addedToFavorites => S.current.addedToFavorites;
  static String get removedFromFavorites => S.current.removedFromFavorites;
  static String get comingSoon => S.current.comingSoon;
  static String get isbn => S.current.isbn;
  static String get viewDetails => S.current.viewDetails;
  static String get scanAgain => S.current.scanAgain;
  static String get bookNotFoundDesc => S.current.bookNotFoundDesc;
}
